FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY apps ./apps
COPY packages ./packages
COPY nx.json ./

RUN yarn install --immutable

EXPOSE 5173

CMD ["yarn", "workspace", "@track-lab/web", "dev:docker"]
