FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY apps ./apps
COPY packages ./packages
COPY nx.json tsconfig.base.json ./

RUN yarn install --immutable

CMD ["yarn", "workspace", "@track-lab/worker", "start"]