FROM node:22-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY apps ./apps
COPY packages ./packages
COPY scripts ./scripts
COPY prisma.config.ts ./
COPY nx.json ./

RUN yarn install --immutable
RUN yarn workspace @track-lab/web build

FROM nginx:alpine

COPY docker/nginx.web.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
