FROM node:22-alpine

WORKDIR /app

# TODO(production): split into build/runtime stages and copy compiled dist output.
RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY apps ./apps
COPY packages ./packages
COPY prisma.config.ts ./
COPY nx.json ./

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

RUN yarn install --immutable

CMD ["yarn", "workspace", "@track-lab/worker", "start:docker"]
